import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { Module } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildSync } from 'esbuild';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, 'src/StockAnalysis.tsx');
assert(existsSync(source), 'The real factor presentation component must exist');
const code = buildSync({ entryPoints: [source], bundle: true, write: false, platform: 'node', format: 'cjs', jsx: 'automatic', external: ['react', 'react-dom/server'] }).outputFiles[0].text;
const compiled = new Module(source);
compiled.filename = source;
compiled.paths = Module._nodeModulePaths(root);
compiled._compile(code, source);
const { FactorBars, PILLAR_META } = compiled.exports;
assert.equal(typeof FactorBars, 'function');
const props = { pillars: { growth: 0, revisions: 76, momentum: 69, valuation: 58, quality: 100 }, scope: 'book', modelVersion: '2026-09-25-five-pillar', isEtf: false };
const render = overrides => renderToStaticMarkup(createElement(FactorBars, { ...props, ...overrides }));
const html = render();
assert.deepEqual(PILLAR_META.map(row => row.label), ['Growth', 'Revisions', 'Momentum', 'Valuation', 'Quality']);
assert.deepEqual([...html.matchAll(/data-factor-key="([^"]+)"/g)].map(match => match[1]), PILLAR_META.map(row => row.key));
assert.match(html, /data-factor-key="growth" data-factor-value="0"/);
assert.match(html, /width:0%/);
assert.match(html, /data-factor-key="quality" data-factor-value="100"/);
assert.match(html, /width:100%/);
assert.match(html, /Book factors/);
assert.match(html, /0–100/);
assert.match(html, /Weight 27\.2%/);
assert(!/0%<\/strong>/.test(html), 'Factor score is not a model weight or return percentage');
console.log('PASS five ordered readable factors, common axis, actual zero, and separately labelled weights');

const etf = render({ isEtf: true });
assert(!etf.includes('data-factor-key='), 'ETF never receives equity-model bars, even if a malformed row includes factors');
assert.match(etf, /ETF.*not scored by the equity model/);
const missing = render({ pillars: null });
assert(!missing.includes('data-factor-key='), 'Missing breakdown does not manufacture five neutral bars');
assert.match(missing, /Factor breakdown not published/);
const invalid = render({ pillars: { growth: null, revisions: -1, momentum: NaN, valuation: Infinity, quality: 101 } });
assert.equal((invalid.match(/data-factor-value="unavailable"/g) || []).length, 5);
assert(!invalid.includes('style="width:'), 'Invalid values do not become clamped or zero-width scores');
console.log('PASS ETF, missing breakdown and invalid factor values remain explicitly unavailable');

const legacy = render({ modelVersion: 'different-model' });
assert(!/\bWeight\s/.test(legacy), 'A different model cannot inherit any current-model factor weight');
assert.match(legacy, /Weights unavailable for this model/);
assert.match(render({ scope: null }), /Score scope unavailable/);
assert.match(render(), /Input coverage not published/);
assert.match(render({ coverage: { inputs_present: 8, thin_inputs: true } }), /8 inputs present/);
assert.match(render({ coverage: { inputs_present: 8, thin_inputs: true } }), /Thin inputs reported/);
assert.match(render({ coverage: { inputs_present: -1, thin_inputs: 'true' } }), /Input coverage not published/);
assert.match(render(), /not expected returns/);
console.log('PASS scope, weight version and coverage are explicit without invented confidence');
